//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Level&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;249&lt;/x&gt;
        ///    &lt;y&gt;164&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;color&gt;Gray&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/powerup&gt;
        ///  &lt;/Brick&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;292&lt;/x&gt;
        ///    &lt;y&gt;183&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;color&gt;Gray&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/powerup&gt;
        ///  &lt;/Brick&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;206&lt;/x&gt;
        ///    &lt;y&gt;164&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;color&gt;Gray&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/poweru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Level&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;298&lt;/x&gt;
        ///    &lt;y&gt;155&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;color&gt;Gray&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/powerup&gt;
        ///  &lt;/Brick&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;255&lt;/x&gt;
        ///    &lt;y&gt;193&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;color&gt;Gray&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/powerup&gt;
        ///  &lt;/Brick&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;255&lt;/x&gt;
        ///    &lt;y&gt;174&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;color&gt;Gray&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/poweru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Level&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;309&lt;/x&gt;
        ///    &lt;y&gt;108&lt;/y&gt;
        ///    &lt;width&gt;18&lt;/width&gt;
        ///    &lt;height&gt;42&lt;/height&gt;
        ///    &lt;hp&gt;4&lt;/hp&gt;
        ///    &lt;color&gt;Purple&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/powerup&gt;
        ///  &lt;/Brick&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;287&lt;/x&gt;
        ///    &lt;y&gt;139&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;4&lt;/hp&gt;
        ///    &lt;color&gt;Purple&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/powerup&gt;
        ///  &lt;/Brick&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;330&lt;/x&gt;
        ///    &lt;y&gt;139&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;4&lt;/hp&gt;
        ///    &lt;color&gt;Purple&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Level&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;290&lt;/x&gt;
        ///    &lt;y&gt;179&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;color&gt;Gray&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/powerup&gt;
        ///  &lt;/Brick&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;290&lt;/x&gt;
        ///    &lt;y&gt;198&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;color&gt;Gray&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/powerup&gt;
        ///  &lt;/Brick&gt;
        ///  &lt;Brick&gt;
        ///    &lt;x&gt;290&lt;/x&gt;
        ///    &lt;y&gt;217&lt;/y&gt;
        ///    &lt;width&gt;42&lt;/width&gt;
        ///    &lt;height&gt;18&lt;/height&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///    &lt;color&gt;Gray&lt;/color&gt;
        ///    &lt;powerup&gt;None&lt;/poweru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ammoBox {
            get {
                object obj = ResourceManager.GetObject("ammoBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chugJugEdited {
            get {
                object obj = ResourceManager.GetObject("chugJugEdited", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Classic_Lobby_Music {
            get {
                return ResourceManager.GetStream("Classic_Lobby_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;HighScore&gt;&lt;HighScore&gt;&lt;score&gt;23&lt;/score&gt;&lt;playerName&gt;Logan&lt;/playerName&gt;&lt;/HighScore&gt;&lt;HighScore&gt;&lt;score&gt;23&lt;/score&gt;&lt;playerName&gt;Logan&lt;/playerName&gt;&lt;/HighScore&gt;&lt;/HighScore&gt;.
        /// </summary>
        internal static string HighScoreXML {
            get {
                return ResourceManager.GetString("HighScoreXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap informationBackground {
            get {
                object obj = ResourceManager.GetObject("informationBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;Level&gt;
        ///&lt;/Level&gt;.
        /// </summary>
        internal static string LevelXML {
            get {
                return ResourceManager.GetString("LevelXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap luckyLandingImage {
            get {
                object obj = ResourceManager.GetObject("luckyLandingImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuScreenBackground {
            get {
                object obj = ResourceManager.GetObject("menuScreenBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pleasantParkImage {
            get {
                object obj = ResourceManager.GetObject("pleasantParkImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap retailRoadImage {
            get {
                object obj = ResourceManager.GetObject("retailRoadImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rocketLauncher {
            get {
                object obj = ResourceManager.GetObject("rocketLauncher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scar {
            get {
                object obj = ResourceManager.GetObject("scar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shotgun {
            get {
                object obj = ResourceManager.GetObject("shotgun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thanos {
            get {
                object obj = ResourceManager.GetObject("thanos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tiltedTowersImage {
            get {
                object obj = ResourceManager.GetObject("tiltedTowersImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
